version: '3.8'
services:
  trademanagementservice:
    image: dtr.demo.dckr.org/demo/dotnetdemo:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==windows
      labels:
        com.docker.ucp.access.label: /Windows
    credential_spec:
      config: credspectest2
    ports:
      - "8150:80"

configs:
  credspectest2:
    external: true
